### ISSUE TITLE
Non linear operation should not be provided, or with a different type

### ISSUE THREAD

**Issue by chambart** [xvw/ppx_measure#1]
For instance there shouldn't be `*` with that type:

```
val ( * ) : ('base,'subtype) t -> ('base,'subtype) t -> ('base,'subtype) t
```

Multiplying two units give the product of the units, not the same unit

One possible simple type is to force one to be a scalar:

```
val ( * ) : float -> ('base,'subtype) t -> ('base,'subtype) t
```

And for some function this is easy:

```
val (/) : ('base,'subtype) t -> ('base,'subtype) t -> float
```

A problematic example would be

```
let%cm a = 1.
let one_square_cm_in_square_cm = Measure.(a * a)
let a_m = Measure.m_of_cm 1.
let one_square_cm_in_square_m = Measure.(a_m * a_m)
let v = Measure.cm_of_m one_square_cm_in_square_m
```

Here `v` will be of type `cm` while it is in fact a `m.cm` which still needs to be converted to cm once more for being in `cm.cm` and be effectively equal to `one_square_cm_in_square_cm`

**Comment by xvw** [comment]
Hum, thanks a lot for your feedback. 
I have some questions : `Multiplying two units give the product of the units, not the same unit`. In fact, 
`('cm, 'cm) Measure.t` is strictly equals to `Measure.cm` because "base units" are not abstract. 

`let v = Measure.cm_of_m one_square_cm_in_square_m` 
But, Measure.cm_of_m doesn't exists? 

I'm sorry if i'm out of place, maybe I don't have understand your purpose?

**Comment by xvw** [comment]
Oh, @drup explain me what do you mean. 
cm \* cm = cm2. 
Thanks.

**Comment by nilsbecker** [comment]
i just stumbled upon this and i agree on the original issue.

the functions sin, cos, exp etc are all nonlinear (or defined in terms of power series) so really they all do not make sense with an input that carries a unit. sin(2 cm) = nonsense. 

what would be meaningful and useful is to allow products of units. basically, something like `val ( * ) : ('base1,'subtype1) t -> ('base2,'subtype2) t -> ('base1 * 'base2, 'subtype12) t` where `'subtype12` multiplies the scaling factors together. but the way i wrote this is also not good since as you accumulate more units, you should get type equality between e.g. `N*(m*s)` and `(N*m)*s`. so one would have to keep a multiset of the base units as a type parameter somehow? no idea if this is feasible in a ppx extension

**Comment by xvw** [comment]
Thanks a lot for your feedback. 
In fact, this extension was just and experiment, but I will rewrite "it" and I will listening all of your feedbacks. 
Thanks a lot !
